// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectRecibos.Services;

#nullable disable

namespace ProyectRecibos.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20241128130802_TheMigration")]
    partial class TheMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProyectRecibos.Models.Recibos", b =>
                {
                    b.Property<float>("ANO")
                        .HasColumnType("real");

                    b.Property<string>("BANCO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("CANTIDAD")
                        .HasColumnType("real");

                    b.Property<float>("CEDULA_NUEVA")
                        .HasColumnType("real");

                    b.Property<string>("CLASIFICACION")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("CODIGO_BANCO")
                        .HasColumnType("real");

                    b.Property<float>("CODIGO_COMPANIA")
                        .HasColumnType("real");

                    b.Property<float>("CODIGO_DEPARTAMENTO")
                        .HasColumnType("real");

                    b.Property<float>("CODIGO_EMPLEADO")
                        .HasColumnType("real");

                    b.Property<float>("CODIGO_FORMA_PAGO")
                        .HasColumnType("real");

                    b.Property<float>("CODIGO_MEDIO_PAGO_NOMINA")
                        .HasColumnType("real");

                    b.Property<float>("CODIGO_MES")
                        .HasColumnType("real");

                    b.Property<float>("CODIGO_PERIODOS_FISCAL")
                        .HasColumnType("real");

                    b.Property<float>("CODIGO_PERIODO_NOMINA")
                        .HasColumnType("real");

                    b.Property<float>("CODIGO_TIPOS_NOMINA")
                        .HasColumnType("real");

                    b.Property<float>("CODIGO_TIPO_EMPLEADO")
                        .HasColumnType("real");

                    b.Property<float>("CODIGO_TURNO")
                        .HasColumnType("real");

                    b.Property<string>("COMPANIA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CONCEPTONOMINA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("DEDUCCION")
                        .HasColumnType("real");

                    b.Property<string>("DEPARTAMENTO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DESCRIPCION")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FECHA_FINAL")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FECHA_INICIAL")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FECHA_PAGO")
                        .HasColumnType("datetime2");

                    b.Property<string>("FORMADEPAGO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("INGRESO")
                        .HasColumnType("real");

                    b.Property<string>("MEDIODEPAGO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("MONTH")
                        .HasColumnType("real");

                    b.Property<string>("NOMBRE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("SUELDO_BASE")
                        .HasColumnType("real");

                    b.Property<string>("TIPOCONCEPTONOMINA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TIPOSNOMINA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("YEAR")
                        .HasColumnType("real");

                    b.ToTable("Recibos");
                });
#pragma warning restore 612, 618
        }
    }
}
